services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - data:/config
      - "${MEDIA_ROOT}:/media"
      - "${DOWNLOADS}:/downloads"
    ports:
      - "8989:8989"
    restart: unless-stopped
volumes:
    data:
