---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8081
      - TORRENTING_PORT=51750
    volumes:
      - data:/config
      - "${MEDIA_ROOT}:/media"
      - "${DOWNLOADS}:/downloads" #optional
    ports:
      - 8081:8081
      - 51750:51750
      - 51750:51750/udp
    restart: unless-stopped
volumes:
    data: