services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - data:/config
      - "${MEDIA_ROOT}:/media"
      - "${DOWNLOADS}:/downloads"
    ports:
      - "7878:7878"
    restart: unless-stopped
volumes:
    data:
