services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    environment:
      - RADARR_URL=${RADARR_URL}
      - SONARR_URL=${SONARR_URL}
      - PROWLARR_URL=${PROWLARR_URL}
      - QBITTORRENT_URL=${QBITTORRENT_URL}
      - AUTOBRR_URL=${AUTOBRR_URL}
      - AUDIOBOOKSHELF_URL=${AUDIOBOOKSHELF_URL}
      - GOTIFY_URL=${GOTIFY_URL}
      - NGINX_PROXY_MANAGER_URL=${NGINX_PROXY_MANAGER_URL}
      - ROUTER_URL=${ROUTER_URL}
      - PROXMOX_URL=${PROXMOX_URL}
      - PROXMOX_API_TOKEN=${PROXMOX_API_TOKEN}
      - PROXMOX_NODE=${PROXMOX_NODE}
      - TRUENAS_URL=${TRUENAS_URL}
      - TRUENAS_API_KEY=${TRUENAS_API_KEY}
      - ADGUARD_USERNAME=${ADGUARD_USERNAME}
      - ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
      - ADGUARD_URL=${ADGUARD_URL}
    volumes:
      - data:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
volumes:
    data: